defaultResources: &defaultResources
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"


global:
  imagePullPolicy: IfNotPresent
  labels:
    project: cloud-iot
    version: "1.0.0"


deployments:
  defaultReplicas: 1

  goApi:
    enabled: true
    replicas: 1
    image: mamarbao/go-api:1.7.0
    sidecarImage: fluent/fluent-bit:2.0.0
    resources: *defaultResources    

  goSimulator:
    enabled: true
    replicas: 1
    image: mamarbao/go-simulator:1.0.0
    sidecarImage: fluent/fluent-bit:2.0.0
    resources: *defaultResources

  iotK8sOperator:
    enabled: false
    replicas: 1
    image: ghcr.io/manujose94/iot-k8s-operator:1.1.0
    resources: {}

  loki:
    enabled: true
    replicas: 1
    image: grafana/loki:latest

  grafana:
    enabled: true
    replicas: 1
    image: grafana/grafana:latest
    
databases:
  enabled: true
  postgres:
    enabled: true
    image: mamarbao/postgres:2.0
    replicas: 1
    configMap:
      DB_HOST: postgres-service
      DB_PORT: "5432"
      DB_TIMEZONE: "Europe/Madrid"

  redis:
    enabled: true
    image: redis
    replicas: 1
    configMap:
      REDIS_HOST: redis-service
      REDIS_PORT: "6379"

secrets:
  postgres:
    user: "mamarbao"
    password: "m4n56l.uc5"
    database: "uc_5"
  
configmaps:
  goApi:
    enabled: true
    resources: {}
    data:
      TEST_PROPUSE: "false"

  fluentBit:
    enabled: true

  goSimulator:
    enabled: true
    resources: {}
    data:
      LATENCY: "5"
      MAX_RETRY_CONNECT: "8"
      RETRY_DELAY_CONNECT: "30"
      
  iotK8sOperator:
    enabled: false
    resources: {}

  fluentBitSimulator:
    enabled: true

services:
  goApi:
    enabled: true
    name: go-api-service
    type: ClusterIP
    port: 80

  loki:
    enabled: true
    name: loki-service
    type: ClusterIP
    port: 3100
    targetPort: 3100

  grafana:
    enabled: false
    name: grafana-service
    type: ClusterIP
    port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: example1.local.com
      serviceName: goApi
      servicePort: 80
    - host: grafana.local.com
      serviceName: grafana
      servicePort: 3000          

# resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

