apiVersion: v2
name: cloud-iot-chart
description: A Helm chart for the Cloud IoT project
version: 0.1.0
dependencies:
  - name: application
    version: 0.1.0
    repository: file://charts/applications
