{{- if and .Values.global .Values.global.labels }}
  {{- include "checkRequiredGlobalLabels" . }}
{{- else }}
  {{- fail "The global configuration 'global' or 'global.labels' is missing" -}}
{{- end }}

{{- if .Values.databases.postgres.enabled }}

{{- if not .Values.secrets }}
{{ fail "The secrets object is missing in the values file." }}
{{- end }}

{{- if not .Values.secrets.postgres }}
{{ fail "The secrets.postgres object is missing in the values file." }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-iot-chart.fullname" . }}-postgres-secret
  labels:
    {{- include "database-chart.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ required "The POSTGRES_USER value is required in secrets.postgres.user" .Values.secrets.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "The POSTGRES_PASSWORD value is required in secrets.postgres.password" .Values.secrets.postgres.password | b64enc | quote }}
  POSTGRES_DB: {{ required "The POSTGRES_DB value is required in secrets.postgres.database" .Values.secrets.postgres.database | b64enc | quote }}
{{- end }}
