apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-iot-chart.fullname" . }}-postgres-secret
  labels:
    {{- include "database-chart.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgres.database | b64enc | quote }}
