name: Helm Chart CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.10.2

      - name: Lint Helm Chart
        run: helm lint ./cloud-iot-chart

  template:
    name: Verify Helm Template Rendering
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.10.2

      - name: Run Helm Template
        run: helm template ./cloud-iot-chart --debug

  manual-test:
    name: Manual Test Helm Chart in Kind Cluster
    runs-on: ubuntu-latest
    needs: [lint, template]
    if: github.event_name == 'workflow_dispatch'
    services:
      kind:
        image: kindest/node:v1.23.0
        options: --privileged
        ports:
          - 6443:6443
        env:
          KIND_EXPERIMENTAL_DOCKER_NETWORK: bridge

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.10.2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.23.0

      - name: Create Kind Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1

      - name: Install Helm Chart in Kind
        run: |
          helm upgrade --install cloud-iot ./cloud-iot-chart \
            --set secrets.postgres.user=$POSTGRES_USER \
            --set secrets.postgres.password=$POSTGRES_PASSWORD \
            --set secrets.postgres.database=$POSTGRES_DB \
            --wait

      - name: Run Helm Tests
        run: helm test cloud-iot
