name: Helm Chart CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Helm Charts Applications Database and monitoring
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        chart-path: [ 'charts/applications' , 'charts/database', 'charts/monitoring']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.10.2
          
      - name: Cache Helm dependencies
        uses: actions/cache@v4.0.2
        with:
          path: ~/.cache/helm
          key: ${{ runner.os }}-helm-${{ hashFiles('**/Chart.yaml') }}
          restore-keys: |
            ${{ runner.os }}-helm-

      - name: Build dependencies for ${{ matrix.chart-path }}
        run: helm dependency build ${{ matrix.chart-path }}

      - name: Lint ${{ matrix.chart-path }} with values file
        run: helm lint ${{ matrix.chart-path }} -f ${{ matrix.chart-path }}/values.yaml    

  template:
    name: Verify Helm Template Rendering
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.10.2

      - name: Run Helm Template on Main Chart
        run: helm template . --debug

  manual-test:
    name: Manual Test Helm Chart in Kind Cluster
    runs-on: ubuntu-latest
    needs: [lint, template]
    if: github.event_name == 'workflow_dispatch'
    services:
      kind:
        image: kindest/node:v1.23.0
        options: --privileged
        ports:
          - 6443:6443
        env:
          KIND_EXPERIMENTAL_DOCKER_NETWORK: bridge

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.10.2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.23.0

      - name: Create Kind Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1

      - name: Install Helm Chart in Kind
        run: |
          helm upgrade --install cloud-iot ./cloud-iot-chart \
            --set secrets.postgres.user=$POSTGRES_USER \
            --set secrets.postgres.password=$POSTGRES_PASSWORD \
            --set secrets.postgres.database=$POSTGRES_DB \
            --wait

      - name: Run Helm Tests
        run: helm test cloud-iot
