global:
  imagePullPolicy: IfNotPresent
  labels:
    project: cloud-iot
    version: "1.0.0"

deployments:
  defaultReplicas: 1
  imagePullPolicy: IfNotPresent

  goApi:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"

  goSimulator:
    enabled: false  # Enable for testing purposes
    replicas: 1

  iotK8sOperator:
    enabled: false  # Enable for testing purposes
    replicas: 1

  loki:
    enabled: true

  grafana:
    enabled: true  # Enable for testing purposes


databases:
  postgres:
    enabled: false
    image: mamarbao/postgres:2.0
    replicas: 1
    
  redis:
    enabled: false


configmaps:
  goApi:
    enabled: true
    data:
      TEST_PROPUSE: "true"

  fluentBit:
    enabled: true

  goSimulator:
    enabled: false  # Enable for testing purposes

  fluentBitSimulator:
    enabled: false

services:
  goApi:
    enabled: true
    name: go-api-service
    type: ClusterIP
    port: 80

  loki:
    enabled: true
    name: loki-service
    type: ClusterIP
    port: 3100
    targetPort: 3100

  grafana:
    enabled: true  # Enable for testing purposes
    name: grafana-service
    type: ClusterIP
    port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: example1.local.com
      serviceName: goApi
      servicePort: 80
    - host: grafana.local.com
      serviceName: grafana
      servicePort: 3000

databases:
  enabled: false  # Enable for testing purposes

serviceAccount:
  create: false
